apiVersion: v1
kind: Service
metadata:
  name: comingsoon-page
  namespace: craftman
spec:
  selector:
    app: mypipe
# ClusterIP (default), LoadBalancer (works on cloud), NodePort (most used)
  type:	LoadBalancer
  ports:
  - protocol: TCP
    port: 9090 
    targetPort: 5000 